### ISSUE TITLE
Support default values in converters

### ISSUE THREAD

**Issue by nevillelyh** [spotify/magnolify#108]
- [x] Avro
- [x] BigQuery
- [x] Bigtable
- [x] Datastore
- [x] Protobuf
- [x] TensorFlow

```scala
scala> import magnolify.bigquery
final package bigquery
scala> import magnolify.bigquery._
import magnolify.bigquery._

scala> case class A(i: Long, j: Long = 10)
class A

scala> val t = TableRowType[A]
val t: magnolify.bigquery.TableRowType[A] = magnolify.bigquery.TableRowType$$anon$1@4b88be62

scala> import com.google.api.services.bigquery.model.TableRow
import com.google.api.services.bigquery.model.TableRow

scala> val tr = new TableRow().set("i", 123)
val tr: com.google.api.services.bigquery.model.TableRow = GenericData{classInfo=[f], {i=123}}

scala> t(tr)
java.lang.NullPointerException
  at magnolify.bigquery.TableRowField$.$anonfun$trfLong$1(TableRowType.scala:132)
  at magnolify.bigquery.TableRowField$.$anonfun$trfLong$1$adapted(TableRowType.scala:132)
  at magnolify.bigquery.TableRowField$$anon$4.from(TableRowType.scala:127)
  at magnolify.bigquery.TableRowField.fromAny(TableRowType.scala:61)
  at magnolify.bigquery.TableRowField.fromAny$(TableRowType.scala:61)
  at magnolify.bigquery.TableRowField$$anon$4.fromAny(TableRowType.scala:124)
  at magnolify.bigquery.TableRowField$$anon$2.$anonfun$from$1(TableRowType.scala:87)
  at $anon$1.construct(<console>:1)
  at $anon$1.construct(<console>:1)
  at magnolify.bigquery.TableRowField$$anon$2.from(TableRowType.scala:87)
  at magnolify.bigquery.TableRowField$$anon$2.from(TableRowType.scala:77)
  at magnolify.bigquery.TableRowType$$anon$1.from(TableRowType.scala:47)
  at magnolify.bigquery.TableRowType$$anon$1.from(TableRowType.scala:43)
  at magnolify.bigquery.TableRowType.apply(TableRowType.scala:37)
  at magnolify.bigquery.TableRowType.apply$(TableRowType.scala:37)
  at magnolify.bigquery.TableRowType$$anon$1.apply(TableRowType.scala:43)
  ... 40 elided
```

**Comment by nevillelyh** [comment]
This might be non-trivial for types that implement their own notion of "default" values, i.e. Avro & Proto 2, since the scala defaults, e.g. `None, Some(1), List(1, 2, 3)` needs to be translated to the Java equivalent of `null, 1, java.util.List()`.

**Comment by nevillelyh** [comment]
#115 adds this for BigQuery, Bigtable & Datastore.
Avro is possible but we need to convert Scala types (array, map, etc) to Java ones and propagate defaults in schema.

**Comment by syodage** [comment]
Above PR is merged and I see Avro also support the default values, and reflected that in the schema too. Does that mean this is fixed? or what else pending?

**Comment by nevillelyh** [comment]
Did you mean #115? That PR doesn't touch `avro`. It's complicated since Avro schema's `"default": ...` supports a limited range of values. Primitives are probably OK. Array, map, etc. might require Scala to Java collection conversion. Records probably not. So we most likely can't support `innerField: Inner = Inner("abc", 123)`.
